server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TL-Lu/spring-cloud-0426.git
          search-paths:
            - configfiles
      label: master